name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: build project for Production
        run: npm run build
      - name: start web application
        run: npm start & 
      - name: Cypress run
        uses: cypress-io/github-action@v2